// Generated by spelloban.py — do not edit by hand.
// Demo week backdated so each puzzle's date matches its difficulty weekday.
window.SPELLOBAN_BAKED = {
  "puzzles": [
    {
      "id": "2026-06-22-mon",
      "terrain": [
        "#######",
        "#.....#",
        "#.....#",
        "#.....#",
        "#.....#",
        "#.....#",
        "#.....#",
        "#.....#",
        "#.....#",
        "#.....#",
        "#.....#",
        "#######"
      ],
      "slots": [
        {
          "pos": [
            4,
            4
          ],
          "letter": "L"
        },
        {
          "pos": [
            5,
            4
          ],
          "letter": "O"
        },
        {
          "pos": [
            6,
            4
          ],
          "letter": "O"
        },
        {
          "pos": [
            7,
            4
          ],
          "letter": "T"
        }
      ],
      "crates": [
        {
          "pos": [
            4,
            4
          ],
          "letter": "T"
        },
        {
          "pos": [
            5,
            4
          ],
          "letter": "O"
        },
        {
          "pos": [
            6,
            4
          ],
          "letter": "O"
        },
        {
          "pos": [
            7,
            4
          ],
          "letter": "L"
        }
      ],
      "player": [
        8,
        1
      ],
      "optimal": 30,
      "anagram": "TOOL",
      "answer": "LOOT",
      "meta": {
        "day": "mon",
        "date": "2026-06-22",
        "M": 43.0,
        "D": 0.0,
        "band": [
          38.7,
          49.4
        ],
        "in_band": true,
        "optimal": 30
      },
      "name": "Mon \u00b7 2026-06-22"
    },
    {
      "id": "2026-06-23-tue",
      "terrain": [
        "#######",
        "#...#.#",
        "#.....#",
        "#.....#",
        "#....##",
        "#.....#",
        "##..#.#",
        "#.....#",
        "#....##",
        "#.#...#",
        "#.....#",
        "#######"
      ],
      "slots": [
        {
          "pos": [
            3,
            3
          ],
          "letter": "W"
        },
        {
          "pos": [
            4,
            3
          ],
          "letter": "E"
        },
        {
          "pos": [
            5,
            3
          ],
          "letter": "I"
        },
        {
          "pos": [
            6,
            3
          ],
          "letter": "R"
        }
      ],
      "crates": [
        {
          "pos": [
            3,
            3
          ],
          "letter": "W"
        },
        {
          "pos": [
            4,
            3
          ],
          "letter": "I"
        },
        {
          "pos": [
            5,
            3
          ],
          "letter": "R"
        },
        {
          "pos": [
            6,
            3
          ],
          "letter": "E"
        }
      ],
      "player": [
        1,
        5
      ],
      "optimal": 41,
      "anagram": "WIRE",
      "answer": "WEIR",
      "meta": {
        "day": "tue",
        "date": "2026-06-23",
        "M": 36.5,
        "D": 0.0,
        "band": [
          35.2,
          44.8
        ],
        "in_band": true,
        "optimal": 41
      },
      "name": "Tue \u00b7 2026-06-23"
    },
    {
      "id": "2026-06-24-wed",
      "terrain": [
        "#######",
        "#.....#",
        "#.....#",
        "#..#..#",
        "#.....#",
        "#.....#",
        "#.....#",
        "##....#",
        "#..#..#",
        "#.....#",
        "#.....#",
        "#######"
      ],
      "slots": [
        {
          "pos": [
            4,
            3
          ],
          "letter": "H"
        },
        {
          "pos": [
            5,
            3
          ],
          "letter": "I"
        },
        {
          "pos": [
            6,
            3
          ],
          "letter": "N"
        },
        {
          "pos": [
            7,
            3
          ],
          "letter": "T"
        }
      ],
      "crates": [
        {
          "pos": [
            4,
            3
          ],
          "letter": "T"
        },
        {
          "pos": [
            5,
            3
          ],
          "letter": "H"
        },
        {
          "pos": [
            6,
            3
          ],
          "letter": "I"
        },
        {
          "pos": [
            7,
            3
          ],
          "letter": "N"
        }
      ],
      "player": [
        9,
        3
      ],
      "optimal": 41,
      "anagram": "THIN",
      "answer": "HINT",
      "meta": {
        "day": "wed",
        "date": "2026-06-24",
        "M": 48.0,
        "D": 0.0,
        "band": [
          36.9,
          48.7
        ],
        "in_band": true,
        "optimal": 41
      },
      "name": "Wed \u00b7 2026-06-24"
    },
    {
      "id": "2026-06-25-thu",
      "terrain": [
        "#######",
        "##....#",
        "#.....#",
        "#.....#",
        "#.....#",
        "#.....#",
        "##....#",
        "#.....#",
        "#.....#",
        "#.....#",
        "#.....#",
        "#######"
      ],
      "slots": [
        {
          "pos": [
            4,
            2
          ],
          "letter": "C"
        },
        {
          "pos": [
            5,
            2
          ],
          "letter": "L"
        },
        {
          "pos": [
            6,
            2
          ],
          "letter": "A"
        },
        {
          "pos": [
            7,
            2
          ],
          "letter": "S"
        },
        {
          "pos": [
            8,
            2
          ],
          "letter": "P"
        }
      ],
      "crates": [
        {
          "pos": [
            4,
            2
          ],
          "letter": "S"
        },
        {
          "pos": [
            5,
            2
          ],
          "letter": "C"
        },
        {
          "pos": [
            6,
            2
          ],
          "letter": "A"
        },
        {
          "pos": [
            7,
            2
          ],
          "letter": "L"
        },
        {
          "pos": [
            8,
            2
          ],
          "letter": "P"
        }
      ],
      "player": [
        1,
        5
      ],
      "optimal": 48,
      "anagram": "SCALP",
      "answer": "CLASP",
      "meta": {
        "day": "thu",
        "date": "2026-06-25",
        "M": 47.5,
        "D": 0.0,
        "band": [
          45.1,
          58.1
        ],
        "in_band": true,
        "optimal": 48
      },
      "name": "Thu \u00b7 2026-06-25"
    },
    {
      "id": "2026-06-26-fri",
      "terrain": [
        "#######",
        "#.....#",
        "#.....#",
        "#.#...#",
        "#.....#",
        "#.....#",
        "##..#.#",
        "#.....#",
        "#.....#",
        "#.....#",
        "#.....#",
        "#######"
      ],
      "slots": [
        {
          "pos": [
            3,
            3
          ],
          "letter": "D"
        },
        {
          "pos": [
            4,
            3
          ],
          "letter": "Y"
        },
        {
          "pos": [
            5,
            3
          ],
          "letter": "I"
        },
        {
          "pos": [
            6,
            3
          ],
          "letter": "N"
        },
        {
          "pos": [
            7,
            3
          ],
          "letter": "G"
        }
      ],
      "crates": [
        {
          "pos": [
            3,
            3
          ],
          "letter": "D"
        },
        {
          "pos": [
            4,
            3
          ],
          "letter": "I"
        },
        {
          "pos": [
            5,
            3
          ],
          "letter": "N"
        },
        {
          "pos": [
            6,
            3
          ],
          "letter": "G"
        },
        {
          "pos": [
            7,
            3
          ],
          "letter": "Y"
        }
      ],
      "player": [
        10,
        2
      ],
      "optimal": 50,
      "anagram": "DINGY",
      "answer": "DYING",
      "meta": {
        "day": "fri",
        "date": "2026-06-26",
        "M": 51.0,
        "D": 0.0,
        "band": [
          50.0,
          66.0
        ],
        "in_band": true,
        "optimal": 50
      },
      "name": "Fri \u00b7 2026-06-26"
    },
    {
      "id": "2026-06-27-sat",
      "terrain": [
        "#######",
        "##....#",
        "#..#..#",
        "#.....#",
        "##....#",
        "#...#.#",
        "#.....#",
        "#..#..#",
        "#.....#",
        "#.#...#",
        "#.....#",
        "#######"
      ],
      "slots": [
        {
          "pos": [
            4,
            2
          ],
          "letter": "C"
        },
        {
          "pos": [
            5,
            2
          ],
          "letter": "O"
        },
        {
          "pos": [
            6,
            2
          ],
          "letter": "A"
        },
        {
          "pos": [
            7,
            2
          ],
          "letter": "S"
        },
        {
          "pos": [
            8,
            2
          ],
          "letter": "T"
        }
      ],
      "crates": [
        {
          "pos": [
            4,
            2
          ],
          "letter": "A"
        },
        {
          "pos": [
            5,
            2
          ],
          "letter": "S"
        },
        {
          "pos": [
            6,
            2
          ],
          "letter": "C"
        },
        {
          "pos": [
            7,
            2
          ],
          "letter": "O"
        },
        {
          "pos": [
            8,
            2
          ],
          "letter": "T"
        }
      ],
      "player": [
        10,
        4
      ],
      "optimal": 103,
      "anagram": "ASCOT",
      "answer": "COAST",
      "meta": {
        "day": "sat",
        "date": "2026-06-27",
        "M": 90.0,
        "D": 0.0,
        "band": [
          81.9,
          110.2
        ],
        "in_band": true,
        "optimal": 103
      },
      "name": "Sat \u00b7 2026-06-27"
    },
    {
      "id": "2026-06-28-sun",
      "terrain": [
        "#######",
        "#.....#",
        "#.....#",
        "#.....#",
        "#.....#",
        "#.....#",
        "#.....#",
        "#.....#",
        "#.....#",
        "#.....#",
        "#.....#",
        "#######"
      ],
      "slots": [
        {
          "pos": [
            3,
            4
          ],
          "letter": "S"
        },
        {
          "pos": [
            4,
            4
          ],
          "letter": "P"
        },
        {
          "pos": [
            5,
            4
          ],
          "letter": "O"
        },
        {
          "pos": [
            6,
            4
          ],
          "letter": "R"
        },
        {
          "pos": [
            7,
            4
          ],
          "letter": "E"
        }
      ],
      "crates": [
        {
          "pos": [
            3,
            4
          ],
          "letter": "P"
        },
        {
          "pos": [
            4,
            4
          ],
          "letter": "R"
        },
        {
          "pos": [
            5,
            4
          ],
          "letter": "O"
        },
        {
          "pos": [
            6,
            4
          ],
          "letter": "S"
        },
        {
          "pos": [
            7,
            4
          ],
          "letter": "E"
        }
      ],
      "player": [
        5,
        2
      ],
      "optimal": 34,
      "anagram": "PROSE",
      "answer": "SPORE",
      "meta": {
        "day": "sun",
        "date": "2026-06-28",
        "M": 25.5,
        "D": 1.3,
        "band": [
          22.9,
          31.9
        ],
        "in_band": true,
        "optimal": 34
      },
      "name": "Sun \u00b7 2026-06-28"
    }
  ],
  "range": [
    "2026-06-22",
    "2026-06-28"
  ]
};
