// Generated by spelloban.py — do not edit by hand.
// Batch 1: 06-22..28 (original). Batch 2: 06-29..07-05 (pillars-only).
// Batch 3: 07-06..12 (footprint-carve + pillars).
window.SPELLOBAN_BAKED = {
  "range": [
    "2026-06-22",
    "2026-07-31"
  ],
  "count": 40,
  "puzzles": [
    {
      "id": "2026-06-22-mon",
      "terrain": [
        "#######",
        "####.##",
        "####.##",
        "####.##",
        "#....##",
        "#....##",
        "#.....#",
        "#.....#",
        "#..#.##",
        "#..#.##",
        "##...##",
        "#######"
      ],
      "slots": [
        {
          "pos": [
            5,
            2
          ],
          "letter": "H"
        },
        {
          "pos": [
            6,
            2
          ],
          "letter": "A"
        },
        {
          "pos": [
            7,
            2
          ],
          "letter": "R"
        },
        {
          "pos": [
            8,
            2
          ],
          "letter": "E"
        }
      ],
      "crates": [
        {
          "pos": [
            5,
            2
          ],
          "letter": "H"
        },
        {
          "pos": [
            6,
            2
          ],
          "letter": "E"
        },
        {
          "pos": [
            7,
            2
          ],
          "letter": "A"
        },
        {
          "pos": [
            8,
            2
          ],
          "letter": "R"
        }
      ],
      "player": [
        1,
        4
      ],
      "optimal": 45,
      "anagram": "HEAR",
      "answer": "HARE",
      "meta": {
        "day": "mon",
        "date": "2026-06-22",
        "M": 25.0,
        "D": 0.0,
        "band": [
          23.8,
          30.0
        ],
        "in_band": true,
        "optimal": 45
      },
      "name": "Mon \u00b7 2026-06-22"
    },
    {
      "id": "2026-06-23-tue",
      "terrain": [
        "#######",
        "#...#.#",
        "#.....#",
        "#.....#",
        "#....##",
        "#.....#",
        "##..#.#",
        "#.....#",
        "#....##",
        "#.#...#",
        "#.....#",
        "#######"
      ],
      "slots": [
        {
          "pos": [
            3,
            3
          ],
          "letter": "W"
        },
        {
          "pos": [
            4,
            3
          ],
          "letter": "E"
        },
        {
          "pos": [
            5,
            3
          ],
          "letter": "I"
        },
        {
          "pos": [
            6,
            3
          ],
          "letter": "R"
        }
      ],
      "crates": [
        {
          "pos": [
            3,
            3
          ],
          "letter": "W"
        },
        {
          "pos": [
            4,
            3
          ],
          "letter": "I"
        },
        {
          "pos": [
            5,
            3
          ],
          "letter": "R"
        },
        {
          "pos": [
            6,
            3
          ],
          "letter": "E"
        }
      ],
      "player": [
        1,
        5
      ],
      "optimal": 41,
      "anagram": "WIRE",
      "answer": "WEIR",
      "meta": {
        "day": "tue",
        "date": "2026-06-23",
        "M": 36.5,
        "D": 0.0,
        "band": [
          35.2,
          44.8
        ],
        "in_band": true,
        "optimal": 41
      },
      "name": "Tue \u00b7 2026-06-23"
    },
    {
      "id": "2026-06-24-wed",
      "terrain": [
        "#######",
        "#.....#",
        "#.....#",
        "#..#..#",
        "#.....#",
        "#.....#",
        "#.....#",
        "##....#",
        "#..#..#",
        "#.....#",
        "#.....#",
        "#######"
      ],
      "slots": [
        {
          "pos": [
            4,
            3
          ],
          "letter": "H"
        },
        {
          "pos": [
            5,
            3
          ],
          "letter": "I"
        },
        {
          "pos": [
            6,
            3
          ],
          "letter": "N"
        },
        {
          "pos": [
            7,
            3
          ],
          "letter": "T"
        }
      ],
      "crates": [
        {
          "pos": [
            4,
            3
          ],
          "letter": "T"
        },
        {
          "pos": [
            5,
            3
          ],
          "letter": "H"
        },
        {
          "pos": [
            6,
            3
          ],
          "letter": "I"
        },
        {
          "pos": [
            7,
            3
          ],
          "letter": "N"
        }
      ],
      "player": [
        9,
        3
      ],
      "optimal": 41,
      "anagram": "THIN",
      "answer": "HINT",
      "meta": {
        "day": "wed",
        "date": "2026-06-24",
        "M": 48.0,
        "D": 0.0,
        "band": [
          36.9,
          48.7
        ],
        "in_band": true,
        "optimal": 41
      },
      "name": "Wed \u00b7 2026-06-24"
    },
    {
      "id": "2026-06-25-thu",
      "terrain": [
        "#######",
        "#######",
        "###...#",
        "#.....#",
        "#....##",
        "###...#",
        "#.....#",
        "#.#...#",
        "#....##",
        "#######",
        "#######",
        "#######"
      ],
      "slots": [
        {
          "pos": [
            4,
            3
          ],
          "letter": "F"
        },
        {
          "pos": [
            5,
            3
          ],
          "letter": "L"
        },
        {
          "pos": [
            6,
            3
          ],
          "letter": "I"
        },
        {
          "pos": [
            7,
            3
          ],
          "letter": "T"
        }
      ],
      "crates": [
        {
          "pos": [
            4,
            3
          ],
          "letter": "L"
        },
        {
          "pos": [
            5,
            3
          ],
          "letter": "I"
        },
        {
          "pos": [
            6,
            3
          ],
          "letter": "F"
        },
        {
          "pos": [
            7,
            3
          ],
          "letter": "T"
        }
      ],
      "player": [
        6,
        1
      ],
      "optimal": 33,
      "anagram": "LIFT",
      "answer": "FLIT",
      "meta": {
        "day": "thu",
        "date": "2026-06-25",
        "M": 28.5,
        "D": 0.0,
        "band": [
          27.5,
          36.2
        ],
        "in_band": true,
        "optimal": 33
      },
      "name": "Thu \u00b7 2026-06-25"
    },
    {
      "id": "2026-06-26-fri",
      "terrain": [
        "#######",
        "#.....#",
        "#.....#",
        "#.#...#",
        "#.....#",
        "#.....#",
        "##..#.#",
        "#.....#",
        "#.....#",
        "#.....#",
        "#.....#",
        "#######"
      ],
      "slots": [
        {
          "pos": [
            3,
            3
          ],
          "letter": "D"
        },
        {
          "pos": [
            4,
            3
          ],
          "letter": "Y"
        },
        {
          "pos": [
            5,
            3
          ],
          "letter": "I"
        },
        {
          "pos": [
            6,
            3
          ],
          "letter": "N"
        },
        {
          "pos": [
            7,
            3
          ],
          "letter": "G"
        }
      ],
      "crates": [
        {
          "pos": [
            3,
            3
          ],
          "letter": "D"
        },
        {
          "pos": [
            4,
            3
          ],
          "letter": "I"
        },
        {
          "pos": [
            5,
            3
          ],
          "letter": "N"
        },
        {
          "pos": [
            6,
            3
          ],
          "letter": "G"
        },
        {
          "pos": [
            7,
            3
          ],
          "letter": "Y"
        }
      ],
      "player": [
        10,
        2
      ],
      "optimal": 50,
      "anagram": "DINGY",
      "answer": "DYING",
      "meta": {
        "day": "fri",
        "date": "2026-06-26",
        "M": 51.0,
        "D": 0.0,
        "band": [
          50.0,
          66.0
        ],
        "in_band": true,
        "optimal": 50
      },
      "name": "Fri \u00b7 2026-06-26"
    },
    {
      "id": "2026-06-27-sat",
      "terrain": [
        "#######",
        "##....#",
        "#..#..#",
        "#.....#",
        "##....#",
        "#...#.#",
        "#.....#",
        "#..#..#",
        "#.....#",
        "#.#...#",
        "#.....#",
        "#######"
      ],
      "slots": [
        {
          "pos": [
            4,
            2
          ],
          "letter": "C"
        },
        {
          "pos": [
            5,
            2
          ],
          "letter": "O"
        },
        {
          "pos": [
            6,
            2
          ],
          "letter": "A"
        },
        {
          "pos": [
            7,
            2
          ],
          "letter": "S"
        },
        {
          "pos": [
            8,
            2
          ],
          "letter": "T"
        }
      ],
      "crates": [
        {
          "pos": [
            4,
            2
          ],
          "letter": "A"
        },
        {
          "pos": [
            5,
            2
          ],
          "letter": "S"
        },
        {
          "pos": [
            6,
            2
          ],
          "letter": "C"
        },
        {
          "pos": [
            7,
            2
          ],
          "letter": "O"
        },
        {
          "pos": [
            8,
            2
          ],
          "letter": "T"
        }
      ],
      "player": [
        10,
        4
      ],
      "optimal": 103,
      "anagram": "ASCOT",
      "answer": "COAST",
      "meta": {
        "day": "sat",
        "date": "2026-06-27",
        "M": 90.0,
        "D": 0.0,
        "band": [
          81.9,
          110.2
        ],
        "in_band": true,
        "optimal": 103
      },
      "name": "Sat \u00b7 2026-06-27"
    },
    {
      "id": "2026-06-28-sun",
      "terrain": [
        "#######",
        "#..####",
        "##.####",
        "#...###",
        "#....##",
        "#....##",
        "##...##",
        "#....##",
        "#....##",
        "#...###",
        "#######",
        "#######"
      ],
      "slots": [
        {
          "pos": [
            5,
            2
          ],
          "letter": "T"
        },
        {
          "pos": [
            6,
            2
          ],
          "letter": "A"
        },
        {
          "pos": [
            7,
            2
          ],
          "letter": "R"
        },
        {
          "pos": [
            8,
            2
          ],
          "letter": "P"
        }
      ],
      "crates": [
        {
          "pos": [
            5,
            2
          ],
          "letter": "R"
        },
        {
          "pos": [
            6,
            2
          ],
          "letter": "A"
        },
        {
          "pos": [
            7,
            2
          ],
          "letter": "P"
        },
        {
          "pos": [
            8,
            2
          ],
          "letter": "T"
        }
      ],
      "player": [
        1,
        1
      ],
      "optimal": 57,
      "anagram": "RAPT",
      "answer": "TARP",
      "meta": {
        "day": "sun",
        "date": "2026-06-28",
        "M": 28.5,
        "D": 2.0,
        "band": [
          28.5,
          37.1
        ],
        "in_band": true,
        "optimal": 57
      },
      "name": "Sun \u00b7 2026-06-28"
    },
    {
      "id": "2026-06-29-mon",
      "terrain": [
        "#######",
        "###.###",
        "###...#",
        "#.....#",
        "#.#...#",
        "#.....#",
        "##....#",
        "##...##",
        "#######",
        "#######",
        "#######",
        "#######"
      ],
      "slots": [
        {
          "pos": [
            3,
            4
          ],
          "letter": "W"
        },
        {
          "pos": [
            4,
            4
          ],
          "letter": "A"
        },
        {
          "pos": [
            5,
            4
          ],
          "letter": "K"
        },
        {
          "pos": [
            6,
            4
          ],
          "letter": "E"
        }
      ],
      "crates": [
        {
          "pos": [
            3,
            4
          ],
          "letter": "W"
        },
        {
          "pos": [
            4,
            4
          ],
          "letter": "E"
        },
        {
          "pos": [
            5,
            4
          ],
          "letter": "A"
        },
        {
          "pos": [
            6,
            4
          ],
          "letter": "K"
        }
      ],
      "player": [
        1,
        3
      ],
      "optimal": 29,
      "anagram": "WEAK",
      "answer": "WAKE",
      "meta": {
        "day": "mon",
        "date": "2026-06-29",
        "M": 25.0,
        "D": 0.0,
        "band": [
          23.8,
          30.0
        ],
        "in_band": true,
        "optimal": 29
      },
      "name": "Mon \u00b7 2026-06-29"
    },
    {
      "id": "2026-06-30-tue",
      "terrain": [
        "#######",
        "#.....#",
        "#.....#",
        "##...##",
        "#.....#",
        "#.....#",
        "#.....#",
        "#.....#",
        "#.....#",
        "#.....#",
        "#..#..#",
        "#######"
      ],
      "slots": [
        {
          "pos": [
            3,
            3
          ],
          "letter": "R"
        },
        {
          "pos": [
            4,
            3
          ],
          "letter": "E"
        },
        {
          "pos": [
            5,
            3
          ],
          "letter": "N"
        },
        {
          "pos": [
            6,
            3
          ],
          "letter": "T"
        }
      ],
      "crates": [
        {
          "pos": [
            3,
            3
          ],
          "letter": "T"
        },
        {
          "pos": [
            4,
            3
          ],
          "letter": "E"
        },
        {
          "pos": [
            5,
            3
          ],
          "letter": "R"
        },
        {
          "pos": [
            6,
            3
          ],
          "letter": "N"
        }
      ],
      "player": [
        8,
        4
      ],
      "optimal": 30,
      "anagram": "TERN",
      "answer": "RENT",
      "meta": {
        "day": "tue",
        "date": "2026-06-30",
        "M": 29.0,
        "D": 0.0,
        "band": [
          26.8,
          34.4
        ],
        "in_band": true,
        "optimal": 30
      },
      "name": "Tue \u00b7 2026-06-30"
    },
    {
      "id": "2026-07-01-wed",
      "terrain": [
        "#######",
        "#.....#",
        "#.....#",
        "#.....#",
        "#.....#",
        "#.....#",
        "#.##..#",
        "#.....#",
        "#..#..#",
        "#.....#",
        "#..#..#",
        "#######"
      ],
      "slots": [
        {
          "pos": [
            4,
            4
          ],
          "letter": "D"
        },
        {
          "pos": [
            5,
            4
          ],
          "letter": "I"
        },
        {
          "pos": [
            6,
            4
          ],
          "letter": "S"
        },
        {
          "pos": [
            7,
            4
          ],
          "letter": "K"
        }
      ],
      "crates": [
        {
          "pos": [
            4,
            4
          ],
          "letter": "S"
        },
        {
          "pos": [
            5,
            4
          ],
          "letter": "K"
        },
        {
          "pos": [
            6,
            4
          ],
          "letter": "I"
        },
        {
          "pos": [
            7,
            4
          ],
          "letter": "D"
        }
      ],
      "player": [
        4,
        2
      ],
      "optimal": 76,
      "anagram": "SKID",
      "answer": "DISK",
      "meta": {
        "day": "wed",
        "date": "2026-07-01",
        "M": 51.5,
        "D": 0.0,
        "band": [
          51.2,
          66.8
        ],
        "in_band": true,
        "optimal": 76
      },
      "name": "Wed \u00b7 2026-07-01"
    },
    {
      "id": "2026-07-02-thu",
      "terrain": [
        "#######",
        "#....##",
        "#.....#",
        "#....##",
        "#.....#",
        "#...#.#",
        "##....#",
        "#.....#",
        "#....##",
        "#...#.#",
        "#.....#",
        "#######"
      ],
      "slots": [
        {
          "pos": [
            5,
            2
          ],
          "letter": "S"
        },
        {
          "pos": [
            6,
            2
          ],
          "letter": "N"
        },
        {
          "pos": [
            7,
            2
          ],
          "letter": "O"
        },
        {
          "pos": [
            8,
            2
          ],
          "letter": "W"
        }
      ],
      "crates": [
        {
          "pos": [
            5,
            2
          ],
          "letter": "S"
        },
        {
          "pos": [
            6,
            2
          ],
          "letter": "O"
        },
        {
          "pos": [
            7,
            2
          ],
          "letter": "W"
        },
        {
          "pos": [
            8,
            2
          ],
          "letter": "N"
        }
      ],
      "player": [
        2,
        5
      ],
      "optimal": 55,
      "anagram": "SOWN",
      "answer": "SNOW",
      "meta": {
        "day": "thu",
        "date": "2026-07-02",
        "M": 39.5,
        "D": 0.0,
        "band": [
          35.2,
          46.4
        ],
        "in_band": true,
        "optimal": 55
      },
      "name": "Thu \u00b7 2026-07-02"
    },
    {
      "id": "2026-07-03-fri",
      "terrain": [
        "#######",
        "#..####",
        "#..#..#",
        "#..##.#",
        "#.....#",
        "#.....#",
        "#.#...#",
        "#.....#",
        "#.....#",
        "#..#..#",
        "#.....#",
        "#######"
      ],
      "slots": [
        {
          "pos": [
            5,
            4
          ],
          "letter": "N"
        },
        {
          "pos": [
            6,
            4
          ],
          "letter": "E"
        },
        {
          "pos": [
            7,
            4
          ],
          "letter": "A"
        },
        {
          "pos": [
            8,
            4
          ],
          "letter": "R"
        }
      ],
      "crates": [
        {
          "pos": [
            5,
            4
          ],
          "letter": "E"
        },
        {
          "pos": [
            6,
            4
          ],
          "letter": "A"
        },
        {
          "pos": [
            7,
            4
          ],
          "letter": "R"
        },
        {
          "pos": [
            8,
            4
          ],
          "letter": "N"
        }
      ],
      "player": [
        3,
        1
      ],
      "optimal": 52,
      "anagram": "EARN",
      "answer": "NEAR",
      "meta": {
        "day": "fri",
        "date": "2026-07-03",
        "M": 48.0,
        "D": 0.0,
        "band": [
          36.9,
          48.7
        ],
        "in_band": true,
        "optimal": 52
      },
      "name": "Fri \u00b7 2026-07-03"
    },
    {
      "id": "2026-07-04-sat",
      "terrain": [
        "#######",
        "#.#...#",
        "#.....#",
        "#..##.#",
        "#.#...#",
        "#.....#",
        "#.....#",
        "###...#",
        "##....#",
        "##....#",
        "##..#.#",
        "#######"
      ],
      "slots": [
        {
          "pos": [
            4,
            3
          ],
          "letter": "D"
        },
        {
          "pos": [
            5,
            3
          ],
          "letter": "I"
        },
        {
          "pos": [
            6,
            3
          ],
          "letter": "V"
        },
        {
          "pos": [
            7,
            3
          ],
          "letter": "E"
        },
        {
          "pos": [
            8,
            3
          ],
          "letter": "R"
        }
      ],
      "crates": [
        {
          "pos": [
            4,
            3
          ],
          "letter": "D"
        },
        {
          "pos": [
            5,
            3
          ],
          "letter": "R"
        },
        {
          "pos": [
            6,
            3
          ],
          "letter": "I"
        },
        {
          "pos": [
            7,
            3
          ],
          "letter": "V"
        },
        {
          "pos": [
            8,
            3
          ],
          "letter": "E"
        }
      ],
      "player": [
        3,
        5
      ],
      "optimal": 68,
      "anagram": "DRIVE",
      "answer": "DIVER",
      "meta": {
        "day": "sat",
        "date": "2026-07-04",
        "M": 47.0,
        "D": 0.0,
        "band": [
          41.3,
          56.0
        ],
        "in_band": true,
        "optimal": 68
      },
      "name": "Sat \u00b7 2026-07-04"
    },
    {
      "id": "2026-07-05-sun",
      "terrain": [
        "#######",
        "#######",
        "#....##",
        "#....##",
        "##...##",
        "#....##",
        "#...###",
        "#...###",
        "##.####",
        "#######",
        "#######",
        "#######"
      ],
      "slots": [
        {
          "pos": [
            3,
            2
          ],
          "letter": "P"
        },
        {
          "pos": [
            4,
            2
          ],
          "letter": "O"
        },
        {
          "pos": [
            5,
            2
          ],
          "letter": "S"
        },
        {
          "pos": [
            6,
            2
          ],
          "letter": "T"
        }
      ],
      "crates": [
        {
          "pos": [
            3,
            2
          ],
          "letter": "S"
        },
        {
          "pos": [
            4,
            2
          ],
          "letter": "P"
        },
        {
          "pos": [
            5,
            2
          ],
          "letter": "O"
        },
        {
          "pos": [
            6,
            2
          ],
          "letter": "T"
        }
      ],
      "player": [
        8,
        2
      ],
      "optimal": 44,
      "anagram": "SPOT",
      "answer": "POST",
      "meta": {
        "day": "sun",
        "date": "2026-07-05",
        "M": 32.0,
        "D": 1.4,
        "band": [
          32.0,
          41.6
        ],
        "in_band": true,
        "optimal": 44
      },
      "name": "Sun \u00b7 2026-07-05"
    },
    {
      "id": "2026-07-06-mon",
      "terrain": [
        "#######",
        "#######",
        "#######",
        "#######",
        "##...##",
        "##....#",
        "##....#",
        "##....#",
        "#.....#",
        "#######",
        "#######",
        "#######"
      ],
      "slots": [
        {
          "pos": [
            4,
            4
          ],
          "letter": "B"
        },
        {
          "pos": [
            5,
            4
          ],
          "letter": "O"
        },
        {
          "pos": [
            6,
            4
          ],
          "letter": "W"
        },
        {
          "pos": [
            7,
            4
          ],
          "letter": "L"
        }
      ],
      "crates": [
        {
          "pos": [
            4,
            4
          ],
          "letter": "B"
        },
        {
          "pos": [
            5,
            4
          ],
          "letter": "L"
        },
        {
          "pos": [
            6,
            4
          ],
          "letter": "O"
        },
        {
          "pos": [
            7,
            4
          ],
          "letter": "W"
        }
      ],
      "player": [
        8,
        1
      ],
      "optimal": 29,
      "anagram": "BLOW",
      "answer": "BOWL",
      "meta": {
        "day": "mon",
        "date": "2026-07-06",
        "M": 25.0,
        "D": 0.0,
        "band": [
          23.8,
          30.0
        ],
        "in_band": true,
        "optimal": 29
      },
      "name": "Mon \u00b7 2026-07-06"
    },
    {
      "id": "2026-07-07-tue",
      "terrain": [
        "#######",
        "##....#",
        "##.#..#",
        "##....#",
        "#.....#",
        "#.....#",
        "#.....#",
        "##.#..#",
        "##...##",
        "#######",
        "#######",
        "#######"
      ],
      "slots": [
        {
          "pos": [
            3,
            3
          ],
          "letter": "V"
        },
        {
          "pos": [
            4,
            3
          ],
          "letter": "I"
        },
        {
          "pos": [
            5,
            3
          ],
          "letter": "N"
        },
        {
          "pos": [
            6,
            3
          ],
          "letter": "E"
        }
      ],
      "crates": [
        {
          "pos": [
            3,
            3
          ],
          "letter": "V"
        },
        {
          "pos": [
            4,
            3
          ],
          "letter": "E"
        },
        {
          "pos": [
            5,
            3
          ],
          "letter": "I"
        },
        {
          "pos": [
            6,
            3
          ],
          "letter": "N"
        }
      ],
      "player": [
        1,
        5
      ],
      "optimal": 30,
      "anagram": "VEIN",
      "answer": "VINE",
      "meta": {
        "day": "tue",
        "date": "2026-07-07",
        "M": 32.0,
        "D": 0.0,
        "band": [
          26.2,
          33.8
        ],
        "in_band": true,
        "optimal": 30
      },
      "name": "Tue \u00b7 2026-07-07"
    },
    {
      "id": "2026-07-08-wed",
      "terrain": [
        "#######",
        "#######",
        "#######",
        "###...#",
        "#.....#",
        "#.....#",
        "#.....#",
        "#..#..#",
        "#.....#",
        "#######",
        "#######",
        "#######"
      ],
      "slots": [
        {
          "pos": [
            4,
            4
          ],
          "letter": "D"
        },
        {
          "pos": [
            5,
            4
          ],
          "letter": "R"
        },
        {
          "pos": [
            6,
            4
          ],
          "letter": "A"
        },
        {
          "pos": [
            7,
            4
          ],
          "letter": "W"
        }
      ],
      "crates": [
        {
          "pos": [
            4,
            4
          ],
          "letter": "W"
        },
        {
          "pos": [
            5,
            4
          ],
          "letter": "A"
        },
        {
          "pos": [
            6,
            4
          ],
          "letter": "R"
        },
        {
          "pos": [
            7,
            4
          ],
          "letter": "D"
        }
      ],
      "player": [
        7,
        1
      ],
      "optimal": 57,
      "anagram": "WARD",
      "answer": "DRAW",
      "meta": {
        "day": "wed",
        "date": "2026-07-08",
        "M": 65.0,
        "D": 0.0,
        "band": [
          51.2,
          66.8
        ],
        "in_band": true,
        "optimal": 57
      },
      "name": "Wed \u00b7 2026-07-08"
    },
    {
      "id": "2026-07-09-thu",
      "terrain": [
        "#######",
        "##..###",
        "#.....#",
        "#...#.#",
        "#.....#",
        "#....##",
        "##...##",
        "#######",
        "#######",
        "#######",
        "#######",
        "#######"
      ],
      "slots": [
        {
          "pos": [
            3,
            2
          ],
          "letter": "S"
        },
        {
          "pos": [
            4,
            2
          ],
          "letter": "L"
        },
        {
          "pos": [
            5,
            2
          ],
          "letter": "I"
        },
        {
          "pos": [
            6,
            2
          ],
          "letter": "P"
        }
      ],
      "crates": [
        {
          "pos": [
            3,
            2
          ],
          "letter": "L"
        },
        {
          "pos": [
            4,
            2
          ],
          "letter": "I"
        },
        {
          "pos": [
            5,
            2
          ],
          "letter": "S"
        },
        {
          "pos": [
            6,
            2
          ],
          "letter": "P"
        }
      ],
      "player": [
        2,
        5
      ],
      "optimal": 41,
      "anagram": "LISP",
      "answer": "SLIP",
      "meta": {
        "day": "thu",
        "date": "2026-07-09",
        "M": 28.5,
        "D": 0.0,
        "band": [
          27.5,
          36.2
        ],
        "in_band": true,
        "optimal": 41
      },
      "name": "Thu \u00b7 2026-07-09"
    },
    {
      "id": "2026-07-10-fri",
      "terrain": [
        "#######",
        "###...#",
        "##....#",
        "#.....#",
        "#....##",
        "##....#",
        "#..#..#",
        "#.##..#",
        "#....##",
        "#######",
        "#######",
        "#######"
      ],
      "slots": [
        {
          "pos": [
            3,
            4
          ],
          "letter": "G"
        },
        {
          "pos": [
            4,
            4
          ],
          "letter": "R"
        },
        {
          "pos": [
            5,
            4
          ],
          "letter": "U"
        },
        {
          "pos": [
            6,
            4
          ],
          "letter": "B"
        }
      ],
      "crates": [
        {
          "pos": [
            3,
            4
          ],
          "letter": "B"
        },
        {
          "pos": [
            4,
            4
          ],
          "letter": "U"
        },
        {
          "pos": [
            5,
            4
          ],
          "letter": "R"
        },
        {
          "pos": [
            6,
            4
          ],
          "letter": "G"
        }
      ],
      "player": [
        8,
        4
      ],
      "optimal": 74,
      "anagram": "BURG",
      "answer": "GRUB",
      "meta": {
        "day": "fri",
        "date": "2026-07-10",
        "M": 58.5,
        "D": 0.0,
        "band": [
          55.6,
          73.4
        ],
        "in_band": true,
        "optimal": 74
      },
      "name": "Fri \u00b7 2026-07-10"
    },
    {
      "id": "2026-07-11-sat",
      "terrain": [
        "#######",
        "###..##",
        "###..##",
        "##...##",
        "#...###",
        "#....##",
        "#....##",
        "#..#.##",
        "#..#.##",
        "#....##",
        "####.##",
        "#######"
      ],
      "slots": [
        {
          "pos": [
            3,
            2
          ],
          "letter": "G"
        },
        {
          "pos": [
            4,
            2
          ],
          "letter": "R"
        },
        {
          "pos": [
            5,
            2
          ],
          "letter": "A"
        },
        {
          "pos": [
            6,
            2
          ],
          "letter": "Z"
        },
        {
          "pos": [
            7,
            2
          ],
          "letter": "E"
        }
      ],
      "crates": [
        {
          "pos": [
            3,
            2
          ],
          "letter": "G"
        },
        {
          "pos": [
            4,
            2
          ],
          "letter": "A"
        },
        {
          "pos": [
            5,
            2
          ],
          "letter": "Z"
        },
        {
          "pos": [
            6,
            2
          ],
          "letter": "E"
        },
        {
          "pos": [
            7,
            2
          ],
          "letter": "R"
        }
      ],
      "player": [
        10,
        4
      ],
      "optimal": 87,
      "anagram": "GAZER",
      "answer": "GRAZE",
      "meta": {
        "day": "sat",
        "date": "2026-07-11",
        "M": 64.5,
        "D": 0.0,
        "band": [
          60.2,
          81.7
        ],
        "in_band": true,
        "optimal": 87
      },
      "name": "Sat \u00b7 2026-07-11"
    },
    {
      "id": "2026-07-12-sun",
      "terrain": [
        "#######",
        "#.#####",
        "#.#####",
        "#.#..##",
        "#....##",
        "#.....#",
        "#...#.#",
        "#.....#",
        "#....##",
        "#.#..##",
        "#....##",
        "#######"
      ],
      "slots": [
        {
          "pos": [
            5,
            3
          ],
          "letter": "M"
        },
        {
          "pos": [
            6,
            3
          ],
          "letter": "E"
        },
        {
          "pos": [
            7,
            3
          ],
          "letter": "S"
        },
        {
          "pos": [
            8,
            3
          ],
          "letter": "A"
        }
      ],
      "crates": [
        {
          "pos": [
            5,
            3
          ],
          "letter": "S"
        },
        {
          "pos": [
            6,
            3
          ],
          "letter": "E"
        },
        {
          "pos": [
            7,
            3
          ],
          "letter": "A"
        },
        {
          "pos": [
            8,
            3
          ],
          "letter": "M"
        }
      ],
      "player": [
        1,
        1
      ],
      "optimal": 54,
      "anagram": "SEAM",
      "answer": "MESA",
      "meta": {
        "day": "sun",
        "date": "2026-07-12",
        "M": 28.5,
        "D": 1.2,
        "band": [
          28.5,
          37.1
        ],
        "in_band": true,
        "optimal": 54
      },
      "name": "Sun \u00b7 2026-07-12"
    },
    {
      "id": "2026-07-13-mon",
      "terrain": [
        "#######",
        "#######",
        "##...##",
        "#....##",
        "#....##",
        "#....##",
        "#....##",
        "###..##",
        "####.##",
        "####..#",
        "#######",
        "#######"
      ],
      "slots": [
        {
          "pos": [
            3,
            3
          ],
          "letter": "N"
        },
        {
          "pos": [
            4,
            3
          ],
          "letter": "E"
        },
        {
          "pos": [
            5,
            3
          ],
          "letter": "O"
        },
        {
          "pos": [
            6,
            3
          ],
          "letter": "N"
        }
      ],
      "crates": [
        {
          "pos": [
            3,
            3
          ],
          "letter": "N"
        },
        {
          "pos": [
            4,
            3
          ],
          "letter": "O"
        },
        {
          "pos": [
            5,
            3
          ],
          "letter": "N"
        },
        {
          "pos": [
            6,
            3
          ],
          "letter": "E"
        }
      ],
      "player": [
        9,
        5
      ],
      "optimal": 38,
      "anagram": "NONE",
      "answer": "NEON",
      "meta": {
        "day": "mon",
        "date": "2026-07-13",
        "M": 32.0,
        "D": 0.0,
        "band": [
          30.4,
          38.4
        ],
        "in_band": true,
        "optimal": 38
      },
      "name": "Mon \u00b7 2026-07-13"
    },
    {
      "id": "2026-07-14-tue",
      "terrain": [
        "#######",
        "#######",
        "#######",
        "####.##",
        "####..#",
        "##....#",
        "#.....#",
        "#.....#",
        "#..#..#",
        "##....#",
        "#######",
        "#######"
      ],
      "slots": [
        {
          "pos": [
            5,
            4
          ],
          "letter": "W"
        },
        {
          "pos": [
            6,
            4
          ],
          "letter": "A"
        },
        {
          "pos": [
            7,
            4
          ],
          "letter": "S"
        },
        {
          "pos": [
            8,
            4
          ],
          "letter": "P"
        }
      ],
      "crates": [
        {
          "pos": [
            5,
            4
          ],
          "letter": "S"
        },
        {
          "pos": [
            6,
            4
          ],
          "letter": "W"
        },
        {
          "pos": [
            7,
            4
          ],
          "letter": "A"
        },
        {
          "pos": [
            8,
            4
          ],
          "letter": "P"
        }
      ],
      "player": [
        3,
        4
      ],
      "optimal": 31,
      "anagram": "SWAP",
      "answer": "WASP",
      "meta": {
        "day": "tue",
        "date": "2026-07-14",
        "M": 34.5,
        "D": 0.0,
        "band": [
          33.6,
          43.2
        ],
        "in_band": true,
        "optimal": 31
      },
      "name": "Tue \u00b7 2026-07-14"
    },
    {
      "id": "2026-07-15-wed",
      "terrain": [
        "#######",
        "#######",
        "##....#",
        "##....#",
        "##..#.#",
        "#.....#",
        "#.#...#",
        "#.#...#",
        "#.#.#.#",
        "#.#.#.#",
        "#.....#",
        "#######"
      ],
      "slots": [
        {
          "pos": [
            3,
            3
          ],
          "letter": "M"
        },
        {
          "pos": [
            4,
            3
          ],
          "letter": "A"
        },
        {
          "pos": [
            5,
            3
          ],
          "letter": "R"
        },
        {
          "pos": [
            6,
            3
          ],
          "letter": "T"
        }
      ],
      "crates": [
        {
          "pos": [
            3,
            3
          ],
          "letter": "T"
        },
        {
          "pos": [
            4,
            3
          ],
          "letter": "R"
        },
        {
          "pos": [
            5,
            3
          ],
          "letter": "A"
        },
        {
          "pos": [
            6,
            3
          ],
          "letter": "M"
        }
      ],
      "player": [
        3,
        5
      ],
      "optimal": 117,
      "anagram": "TRAM",
      "answer": "MART",
      "meta": {
        "day": "wed",
        "date": "2026-07-15",
        "M": 69.5,
        "D": 0.0,
        "band": [
          55.8,
          72.8
        ],
        "in_band": true,
        "optimal": 117
      },
      "name": "Wed \u00b7 2026-07-15"
    },
    {
      "id": "2026-07-16-thu",
      "terrain": [
        "#######",
        "#...###",
        "#....##",
        "##....#",
        "#.....#",
        "#.....#",
        "#...###",
        "#######",
        "#######",
        "#######",
        "#######",
        "#######"
      ],
      "slots": [
        {
          "pos": [
            3,
            3
          ],
          "letter": "S"
        },
        {
          "pos": [
            4,
            3
          ],
          "letter": "H"
        },
        {
          "pos": [
            5,
            3
          ],
          "letter": "O"
        },
        {
          "pos": [
            6,
            3
          ],
          "letter": "T"
        }
      ],
      "crates": [
        {
          "pos": [
            3,
            3
          ],
          "letter": "H"
        },
        {
          "pos": [
            4,
            3
          ],
          "letter": "O"
        },
        {
          "pos": [
            5,
            3
          ],
          "letter": "S"
        },
        {
          "pos": [
            6,
            3
          ],
          "letter": "T"
        }
      ],
      "player": [
        6,
        1
      ],
      "optimal": 42,
      "anagram": "HOST",
      "answer": "SHOT",
      "meta": {
        "day": "thu",
        "date": "2026-07-16",
        "M": 28.5,
        "D": 0.0,
        "band": [
          27.5,
          36.2
        ],
        "in_band": true,
        "optimal": 42
      },
      "name": "Thu \u00b7 2026-07-16"
    },
    {
      "id": "2026-07-17-fri",
      "terrain": [
        "#######",
        "#.....#",
        "#..#..#",
        "#..##.#",
        "#.#...#",
        "#.....#",
        "#...#.#",
        "#.....#",
        "#....##",
        "###..##",
        "#######",
        "#######"
      ],
      "slots": [
        {
          "pos": [
            5,
            2
          ],
          "letter": "M"
        },
        {
          "pos": [
            6,
            2
          ],
          "letter": "A"
        },
        {
          "pos": [
            7,
            2
          ],
          "letter": "S"
        },
        {
          "pos": [
            8,
            2
          ],
          "letter": "H"
        }
      ],
      "crates": [
        {
          "pos": [
            5,
            2
          ],
          "letter": "S"
        },
        {
          "pos": [
            6,
            2
          ],
          "letter": "H"
        },
        {
          "pos": [
            7,
            2
          ],
          "letter": "A"
        },
        {
          "pos": [
            8,
            2
          ],
          "letter": "M"
        }
      ],
      "player": [
        5,
        5
      ],
      "optimal": 78,
      "anagram": "SHAM",
      "answer": "MASH",
      "meta": {
        "day": "fri",
        "date": "2026-07-17",
        "M": 56.0,
        "D": 0.0,
        "band": [
          55.6,
          73.4
        ],
        "in_band": true,
        "optimal": 78
      },
      "name": "Fri \u00b7 2026-07-17"
    },
    {
      "id": "2026-07-18-sat",
      "terrain": [
        "#######",
        "##....#",
        "#..#..#",
        "#.....#",
        "##.#..#",
        "#....##",
        "#..#.##",
        "#.....#",
        "#.#...#",
        "#.##..#",
        "#.#####",
        "#######"
      ],
      "slots": [
        {
          "pos": [
            3,
            2
          ],
          "letter": "A"
        },
        {
          "pos": [
            4,
            2
          ],
          "letter": "M"
        },
        {
          "pos": [
            5,
            2
          ],
          "letter": "B"
        },
        {
          "pos": [
            6,
            2
          ],
          "letter": "L"
        },
        {
          "pos": [
            7,
            2
          ],
          "letter": "E"
        }
      ],
      "crates": [
        {
          "pos": [
            3,
            2
          ],
          "letter": "B"
        },
        {
          "pos": [
            4,
            2
          ],
          "letter": "L"
        },
        {
          "pos": [
            5,
            2
          ],
          "letter": "A"
        },
        {
          "pos": [
            6,
            2
          ],
          "letter": "M"
        },
        {
          "pos": [
            7,
            2
          ],
          "letter": "E"
        }
      ],
      "player": [
        10,
        1
      ],
      "optimal": 103,
      "anagram": "BLAME",
      "answer": "AMBLE",
      "meta": {
        "day": "sat",
        "date": "2026-07-18",
        "M": 81.5,
        "D": 0.0,
        "band": [
          79.1,
          107.3
        ],
        "in_band": true,
        "optimal": 103
      },
      "name": "Sat \u00b7 2026-07-18"
    },
    {
      "id": "2026-07-19-sun",
      "terrain": [
        "#######",
        "##...##",
        "#..#.##",
        "#....##",
        "#....##",
        "#...###",
        "#...###",
        "##..###",
        "#######",
        "#######",
        "#######",
        "#######"
      ],
      "slots": [
        {
          "pos": [
            3,
            2
          ],
          "letter": "F"
        },
        {
          "pos": [
            4,
            2
          ],
          "letter": "O"
        },
        {
          "pos": [
            5,
            2
          ],
          "letter": "W"
        },
        {
          "pos": [
            6,
            2
          ],
          "letter": "L"
        }
      ],
      "crates": [
        {
          "pos": [
            3,
            2
          ],
          "letter": "W"
        },
        {
          "pos": [
            4,
            2
          ],
          "letter": "O"
        },
        {
          "pos": [
            5,
            2
          ],
          "letter": "L"
        },
        {
          "pos": [
            6,
            2
          ],
          "letter": "F"
        }
      ],
      "player": [
        1,
        3
      ],
      "optimal": 39,
      "anagram": "WOLF",
      "answer": "FOWL",
      "meta": {
        "day": "sun",
        "date": "2026-07-19",
        "M": 28.5,
        "D": 1.1,
        "band": [
          28.5,
          37.1
        ],
        "in_band": true,
        "optimal": 39
      },
      "name": "Sun \u00b7 2026-07-19"
    },
    {
      "id": "2026-07-20-mon",
      "terrain": [
        "#######",
        "#.#####",
        "#.#####",
        "#.#..##",
        "#.....#",
        "#..#..#",
        "#.....#",
        "#....##",
        "#....##",
        "#######",
        "#######",
        "#######"
      ],
      "slots": [
        {
          "pos": [
            4,
            2
          ],
          "letter": "C"
        },
        {
          "pos": [
            5,
            2
          ],
          "letter": "O"
        },
        {
          "pos": [
            6,
            2
          ],
          "letter": "I"
        },
        {
          "pos": [
            7,
            2
          ],
          "letter": "N"
        }
      ],
      "crates": [
        {
          "pos": [
            4,
            2
          ],
          "letter": "I"
        },
        {
          "pos": [
            5,
            2
          ],
          "letter": "C"
        },
        {
          "pos": [
            6,
            2
          ],
          "letter": "O"
        },
        {
          "pos": [
            7,
            2
          ],
          "letter": "N"
        }
      ],
      "player": [
        1,
        1
      ],
      "optimal": 46,
      "anagram": "ICON",
      "answer": "COIN",
      "meta": {
        "day": "mon",
        "date": "2026-07-20",
        "M": 32.0,
        "D": 0.0,
        "band": [
          30.4,
          38.4
        ],
        "in_band": true,
        "optimal": 46
      },
      "name": "Mon \u00b7 2026-07-20"
    },
    {
      "id": "2026-07-21-tue",
      "terrain": [
        "#######",
        "#######",
        "###.###",
        "###.###",
        "#....##",
        "#....##",
        "#..####",
        "#....##",
        "#....##",
        "#....##",
        "#....##",
        "#######"
      ],
      "slots": [
        {
          "pos": [
            5,
            2
          ],
          "letter": "A"
        },
        {
          "pos": [
            6,
            2
          ],
          "letter": "L"
        },
        {
          "pos": [
            7,
            2
          ],
          "letter": "M"
        },
        {
          "pos": [
            8,
            2
          ],
          "letter": "S"
        }
      ],
      "crates": [
        {
          "pos": [
            5,
            2
          ],
          "letter": "S"
        },
        {
          "pos": [
            6,
            2
          ],
          "letter": "L"
        },
        {
          "pos": [
            7,
            2
          ],
          "letter": "A"
        },
        {
          "pos": [
            8,
            2
          ],
          "letter": "M"
        }
      ],
      "player": [
        2,
        3
      ],
      "optimal": 75,
      "anagram": "SLAM",
      "answer": "ALMS",
      "meta": {
        "day": "tue",
        "date": "2026-07-21",
        "M": 31.5,
        "D": 0.0,
        "band": [
          26.8,
          34.4
        ],
        "in_band": true,
        "optimal": 75
      },
      "name": "Tue \u00b7 2026-07-21"
    },
    {
      "id": "2026-07-22-wed",
      "terrain": [
        "#######",
        "#######",
        "#######",
        "####..#",
        "#.....#",
        "#.#...#",
        "#.....#",
        "#.#...#",
        "#....##",
        "#....##",
        "#######",
        "#######"
      ],
      "slots": [
        {
          "pos": [
            5,
            4
          ],
          "letter": "M"
        },
        {
          "pos": [
            6,
            4
          ],
          "letter": "O"
        },
        {
          "pos": [
            7,
            4
          ],
          "letter": "A"
        },
        {
          "pos": [
            8,
            4
          ],
          "letter": "T"
        }
      ],
      "crates": [
        {
          "pos": [
            5,
            4
          ],
          "letter": "A"
        },
        {
          "pos": [
            6,
            4
          ],
          "letter": "T"
        },
        {
          "pos": [
            7,
            4
          ],
          "letter": "O"
        },
        {
          "pos": [
            8,
            4
          ],
          "letter": "M"
        }
      ],
      "player": [
        9,
        1
      ],
      "optimal": 74,
      "anagram": "ATOM",
      "answer": "MOAT",
      "meta": {
        "day": "wed",
        "date": "2026-07-22",
        "M": 51.5,
        "D": 0.0,
        "band": [
          51.2,
          66.8
        ],
        "in_band": true,
        "optimal": 74
      },
      "name": "Wed \u00b7 2026-07-22"
    },
    {
      "id": "2026-07-23-thu",
      "terrain": [
        "#######",
        "#######",
        "##...##",
        "##...##",
        "##..###",
        "#....##",
        "#.....#",
        "#...#.#",
        "#.....#",
        "##..###",
        "#######",
        "#######"
      ],
      "slots": [
        {
          "pos": [
            4,
            2
          ],
          "letter": "M"
        },
        {
          "pos": [
            5,
            2
          ],
          "letter": "A"
        },
        {
          "pos": [
            6,
            2
          ],
          "letter": "U"
        },
        {
          "pos": [
            7,
            2
          ],
          "letter": "L"
        }
      ],
      "crates": [
        {
          "pos": [
            4,
            2
          ],
          "letter": "A"
        },
        {
          "pos": [
            5,
            2
          ],
          "letter": "L"
        },
        {
          "pos": [
            6,
            2
          ],
          "letter": "U"
        },
        {
          "pos": [
            7,
            2
          ],
          "letter": "M"
        }
      ],
      "player": [
        2,
        4
      ],
      "optimal": 63,
      "anagram": "ALUM",
      "answer": "MAUL",
      "meta": {
        "day": "thu",
        "date": "2026-07-23",
        "M": 29.0,
        "D": 0.0,
        "band": [
          28.1,
          37.0
        ],
        "in_band": true,
        "optimal": 63
      },
      "name": "Thu \u00b7 2026-07-23"
    },
    {
      "id": "2026-07-24-fri",
      "terrain": [
        "#######",
        "#######",
        "###...#",
        "##..#.#",
        "##....#",
        "#.....#",
        "#...###",
        "#...###",
        "#.#.###",
        "#...###",
        "#######",
        "#######"
      ],
      "slots": [
        {
          "pos": [
            4,
            2
          ],
          "letter": "P"
        },
        {
          "pos": [
            5,
            2
          ],
          "letter": "R"
        },
        {
          "pos": [
            6,
            2
          ],
          "letter": "O"
        },
        {
          "pos": [
            7,
            2
          ],
          "letter": "M"
        }
      ],
      "crates": [
        {
          "pos": [
            4,
            2
          ],
          "letter": "R"
        },
        {
          "pos": [
            5,
            2
          ],
          "letter": "O"
        },
        {
          "pos": [
            6,
            2
          ],
          "letter": "M"
        },
        {
          "pos": [
            7,
            2
          ],
          "letter": "P"
        }
      ],
      "player": [
        9,
        2
      ],
      "optimal": 59,
      "anagram": "ROMP",
      "answer": "PROM",
      "meta": {
        "day": "fri",
        "date": "2026-07-24",
        "M": 48.5,
        "D": 0.0,
        "band": [
          36.9,
          48.7
        ],
        "in_band": true,
        "optimal": 59
      },
      "name": "Fri \u00b7 2026-07-24"
    },
    {
      "id": "2026-07-25-sat",
      "terrain": [
        "#######",
        "#######",
        "###.###",
        "###...#",
        "###...#",
        "##...##",
        "##....#",
        "##....#",
        "##....#",
        "##.#..#",
        "##....#",
        "#######"
      ],
      "slots": [
        {
          "pos": [
            4,
            4
          ],
          "letter": "U"
        },
        {
          "pos": [
            5,
            4
          ],
          "letter": "P"
        },
        {
          "pos": [
            6,
            4
          ],
          "letter": "S"
        },
        {
          "pos": [
            7,
            4
          ],
          "letter": "E"
        },
        {
          "pos": [
            8,
            4
          ],
          "letter": "T"
        }
      ],
      "crates": [
        {
          "pos": [
            4,
            4
          ],
          "letter": "S"
        },
        {
          "pos": [
            5,
            4
          ],
          "letter": "E"
        },
        {
          "pos": [
            6,
            4
          ],
          "letter": "T"
        },
        {
          "pos": [
            7,
            4
          ],
          "letter": "U"
        },
        {
          "pos": [
            8,
            4
          ],
          "letter": "P"
        }
      ],
      "player": [
        2,
        3
      ],
      "optimal": 96,
      "anagram": "SETUP",
      "answer": "UPSET",
      "meta": {
        "day": "sat",
        "date": "2026-07-25",
        "M": 75.0,
        "D": 0.0,
        "band": [
          70.7,
          95.9
        ],
        "in_band": true,
        "optimal": 96
      },
      "name": "Sat \u00b7 2026-07-25"
    },
    {
      "id": "2026-07-26-sun",
      "terrain": [
        "#######",
        "#######",
        "##...##",
        "##...##",
        "#....##",
        "#.....#",
        "#...#.#",
        "#.....#",
        "#######",
        "#######",
        "#######",
        "#######"
      ],
      "slots": [
        {
          "pos": [
            3,
            3
          ],
          "letter": "T"
        },
        {
          "pos": [
            4,
            3
          ],
          "letter": "A"
        },
        {
          "pos": [
            5,
            3
          ],
          "letter": "M"
        },
        {
          "pos": [
            6,
            3
          ],
          "letter": "E"
        }
      ],
      "crates": [
        {
          "pos": [
            3,
            3
          ],
          "letter": "T"
        },
        {
          "pos": [
            4,
            3
          ],
          "letter": "E"
        },
        {
          "pos": [
            5,
            3
          ],
          "letter": "A"
        },
        {
          "pos": [
            6,
            3
          ],
          "letter": "M"
        }
      ],
      "player": [
        4,
        1
      ],
      "optimal": 37,
      "anagram": "TEAM",
      "answer": "TAME",
      "meta": {
        "day": "sun",
        "date": "2026-07-26",
        "M": 25.0,
        "D": 2.5,
        "band": [
          25.0,
          32.5
        ],
        "in_band": true,
        "optimal": 37
      },
      "name": "Sun \u00b7 2026-07-26"
    },
    {
      "id": "2026-07-27-mon",
      "terrain": [
        "#######",
        "#######",
        "#######",
        "#######",
        "#....##",
        "#....##",
        "#....##",
        "#....##",
        "#....##",
        "#..#.##",
        "#....##",
        "#######"
      ],
      "slots": [
        {
          "pos": [
            5,
            2
          ],
          "letter": "T"
        },
        {
          "pos": [
            6,
            2
          ],
          "letter": "O"
        },
        {
          "pos": [
            7,
            2
          ],
          "letter": "G"
        },
        {
          "pos": [
            8,
            2
          ],
          "letter": "A"
        }
      ],
      "crates": [
        {
          "pos": [
            5,
            2
          ],
          "letter": "G"
        },
        {
          "pos": [
            6,
            2
          ],
          "letter": "O"
        },
        {
          "pos": [
            7,
            2
          ],
          "letter": "A"
        },
        {
          "pos": [
            8,
            2
          ],
          "letter": "T"
        }
      ],
      "player": [
        10,
        2
      ],
      "optimal": 41,
      "anagram": "GOAT",
      "answer": "TOGA",
      "meta": {
        "day": "mon",
        "date": "2026-07-27",
        "M": 28.5,
        "D": 0.0,
        "band": [
          27.1,
          34.2
        ],
        "in_band": true,
        "optimal": 41
      },
      "name": "Mon \u00b7 2026-07-27"
    },
    {
      "id": "2026-07-28-tue",
      "terrain": [
        "#######",
        "#######",
        "##....#",
        "#####.#",
        "#####.#",
        "##.#..#",
        "#.....#",
        "#.....#",
        "#.....#",
        "#.....#",
        "#######",
        "#######"
      ],
      "slots": [
        {
          "pos": [
            5,
            2
          ],
          "letter": "W"
        },
        {
          "pos": [
            6,
            2
          ],
          "letter": "E"
        },
        {
          "pos": [
            7,
            2
          ],
          "letter": "A"
        },
        {
          "pos": [
            8,
            2
          ],
          "letter": "R"
        }
      ],
      "crates": [
        {
          "pos": [
            5,
            2
          ],
          "letter": "W"
        },
        {
          "pos": [
            6,
            2
          ],
          "letter": "A"
        },
        {
          "pos": [
            7,
            2
          ],
          "letter": "R"
        },
        {
          "pos": [
            8,
            2
          ],
          "letter": "E"
        }
      ],
      "player": [
        2,
        2
      ],
      "optimal": 42,
      "anagram": "WARE",
      "answer": "WEAR",
      "meta": {
        "day": "tue",
        "date": "2026-07-28",
        "M": 34.5,
        "D": 0.0,
        "band": [
          33.6,
          43.2
        ],
        "in_band": true,
        "optimal": 42
      },
      "name": "Tue \u00b7 2026-07-28"
    },
    {
      "id": "2026-07-29-wed",
      "terrain": [
        "#######",
        "###...#",
        "#.....#",
        "#.#...#",
        "#.....#",
        "###...#",
        "###...#",
        "###.#.#",
        "###...#",
        "#######",
        "#######",
        "#######"
      ],
      "slots": [
        {
          "pos": [
            3,
            4
          ],
          "letter": "P"
        },
        {
          "pos": [
            4,
            4
          ],
          "letter": "R"
        },
        {
          "pos": [
            5,
            4
          ],
          "letter": "A"
        },
        {
          "pos": [
            6,
            4
          ],
          "letter": "M"
        }
      ],
      "crates": [
        {
          "pos": [
            3,
            4
          ],
          "letter": "R"
        },
        {
          "pos": [
            4,
            4
          ],
          "letter": "A"
        },
        {
          "pos": [
            5,
            4
          ],
          "letter": "M"
        },
        {
          "pos": [
            6,
            4
          ],
          "letter": "P"
        }
      ],
      "player": [
        2,
        2
      ],
      "optimal": 56,
      "anagram": "RAMP",
      "answer": "PRAM",
      "meta": {
        "day": "wed",
        "date": "2026-07-29",
        "M": 40.5,
        "D": 0.0,
        "band": [
          33.9,
          44.2
        ],
        "in_band": true,
        "optimal": 56
      },
      "name": "Wed \u00b7 2026-07-29"
    },
    {
      "id": "2026-07-30-thu",
      "terrain": [
        "#######",
        "#######",
        "#######",
        "###...#",
        "#.....#",
        "#....##",
        "#.#...#",
        "#.....#",
        "#.....#",
        "####.##",
        "####..#",
        "#######"
      ],
      "slots": [
        {
          "pos": [
            4,
            3
          ],
          "letter": "B"
        },
        {
          "pos": [
            5,
            3
          ],
          "letter": "A"
        },
        {
          "pos": [
            6,
            3
          ],
          "letter": "L"
        },
        {
          "pos": [
            7,
            3
          ],
          "letter": "M"
        }
      ],
      "crates": [
        {
          "pos": [
            4,
            3
          ],
          "letter": "L"
        },
        {
          "pos": [
            5,
            3
          ],
          "letter": "A"
        },
        {
          "pos": [
            6,
            3
          ],
          "letter": "M"
        },
        {
          "pos": [
            7,
            3
          ],
          "letter": "B"
        }
      ],
      "player": [
        10,
        5
      ],
      "optimal": 45,
      "anagram": "LAMB",
      "answer": "BALM",
      "meta": {
        "day": "thu",
        "date": "2026-07-30",
        "M": 36.5,
        "D": 0.0,
        "band": [
          31.4,
          41.3
        ],
        "in_band": true,
        "optimal": 45
      },
      "name": "Thu \u00b7 2026-07-30"
    },
    {
      "id": "2026-07-31-fri",
      "terrain": [
        "#######",
        "##....#",
        "#...#.#",
        "#..#..#",
        "#....##",
        "#.....#",
        "#...#.#",
        "#.....#",
        "#######",
        "#######",
        "#######",
        "#######"
      ],
      "slots": [
        {
          "pos": [
            3,
            2
          ],
          "letter": "A"
        },
        {
          "pos": [
            4,
            2
          ],
          "letter": "V"
        },
        {
          "pos": [
            5,
            2
          ],
          "letter": "I"
        },
        {
          "pos": [
            6,
            2
          ],
          "letter": "D"
        }
      ],
      "crates": [
        {
          "pos": [
            3,
            2
          ],
          "letter": "D"
        },
        {
          "pos": [
            4,
            2
          ],
          "letter": "I"
        },
        {
          "pos": [
            5,
            2
          ],
          "letter": "V"
        },
        {
          "pos": [
            6,
            2
          ],
          "letter": "A"
        }
      ],
      "player": [
        2,
        5
      ],
      "optimal": 64,
      "anagram": "DIVA",
      "answer": "AVID",
      "meta": {
        "day": "fri",
        "date": "2026-07-31",
        "M": 58.0,
        "D": 0.0,
        "band": [
          55.6,
          73.4
        ],
        "in_band": true,
        "optimal": 64
      },
      "name": "Fri \u00b7 2026-07-31"
    }
  ]
};
